[package]

name = "plugin"
version = "0.0.1"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
description = "Lazily evaluated, order-independent plugins for extensible types."
repository = "https://github.com/reem/rust-plugin"
license = "MIT"

[dependencies]
typemap = "*"
phantom = "*"

